sw-rails/config/routes.rb
SwRails::Application.routes.draw do

  root :to => "home#index"

  get "/profiles/:id/career" => "profiles#career"
  get "/profiles/:id/batting" => "profiles#batting"
  get "/profiles/:id/bowling" => "profiles#bowling"

  get "/records" => "records#index"
  get "/records/runs/:scope/:order" => "records#runs"

  get "/admin" => "common#admin"

  resources :extra_types
  resources :dismissal_types
  resources :matches
  resources :opposition_teams
  resources :player_aliases
  resources :grades
  resources :competition_genres
  resources :teams
  resources :competitions
  resources :seasons
  resources :nicknames
  resources :profiles
  resources :memberships
  resources :clubs
  resources :players
  
end

sw-rails/app/models/ball.rb
class Ball < ActiveRecord::Base

  belongs_to :batsman_innings
  belongs_to :over
  belongs_to :dismissal_type
  belongs_to :extra_type

  def category
    return '7+' if batsman_value >= 7
    return '5' if batsman_value >= 5
    return '3-4' if batsman_value >= 3
    return '1' if batsman_value == 1
    return 'Dot' if batsman_value == 0
    return 'Extra' unless extra_type.nil?
    return 'Wicket' unless dismissal_type.nil?
    return '2' if batsman_value == 2
    return score
  end

end

sw-rails/app/models/bat_innings.rb
class BatInnings < ActiveRecord::Base

  belongs_to :player
  
end

sw-rails/app/models/batsman_innings.rb
class BatsmanInnings < ActiveRecord::Base

  belongs_to :match
  belongs_to :player
  has_many :balls

  def self.find_all_by_filter(order, filter)

    limit = filter[:limit] || 50
    order_sql = (order == 'desc') ? 'order by runs desc, bf asc' : 'order by runs asc, bf desc'
    tables = {'batsman_innings' => 'bi', 'balls' => 'b'}
    clause = ""
    params = []

    if filter[:season_id]
      tables['seasons'] = 's'
      tables['matches'] = 'm'
      tables['teams'] = 't'
      clause += "m.team_id = t.id and bi.match_id = m.id and t.season_id = s.id and s.id = #{filter[:season_id]} and "
    end

    if filter[:player_id]
      clause += "bi.player_id in (#{filter[:player_id]})"
    end

    tables_str = ""
    tables.each{|x,y|tables_str += "#{x} #{y}," }
    tables_str = tables_str[0..-2]

    sql = "select bi.*, sum(b.batsman_value) runs, count(b.batsman_value) bf " +
            "from #{tables_str} " +
            "where #{clause} bi.id = b.batsman_innings_id " +
            "group by bi.id " +
            "#{order_sql} " +
            "limit #{limit}"

    connection.execute(sql)
  end

  def score
    runs = 0
    balls.each do |ball|
      runs += ball.batsman_value
    end
    runs
  end

  def bf
    balls.count
  end

end

sw-rails/app/models/club.rb
class Club < ActiveRecord::Base

  

end

sw-rails/app/models/competition.rb
class Competition < ActiveRecord::Base

  belongs_to :competition_genre

end

sw-rails/app/models/dismissal_type.rb
class DismissalType < ActiveRecord::Base
end

sw-rails/app/models/extra_type.rb
class ExtraType < ActiveRecord::Base
end

sw-rails/app/models/grade.rb
class Grade < ActiveRecord::Base
end

sw-rails/app/models/match.rb
class Match < ActiveRecord::Base

  belongs_to :team
  belongs_to :opposition_team
  has_many :batsman_inningss
  has_many :overs

end

sw-rails/app/models/membership.rb
class Membership < ActiveRecord::Base
end

sw-rails/app/models/nickname.rb
class Nickname < ActiveRecord::Base

  belongs_to :player
  
end

sw-rails/app/models/opposition_team.rb
class OppositionTeam < ActiveRecord::Base
end

sw-rails/app/models/over.rb
class Over < ActiveRecord::Base

  belongs_to :match
  belongs_to :player
  has_many :balls


  def score
    runs = 0
    balls.each do |ball|
      runs += ball.bowler_value
    end
    runs
  end

  def bf
    balls.count
  end

  def extras
    balls.select{|b|!b.extra_type.nil?}.count
  end

  def wickets
    balls.select{|b|!b.dismissal_type.nil?}.count
  end

end

sw-rails/app/models/player.rb
class Player < ActiveRecord::Base

  has_many :player_aliases
  has_many :nicknames
  has_one :profile

  def display
    profile.nil? ? code : profile.display
  end

  def name
    profile.nil? ? code : profile.name
  end

end

sw-rails/app/models/player_alias.rb
class PlayerAlias < ActiveRecord::Base

  belongs_to :player
  
end

sw-rails/app/models/profile.rb
class Profile < ActiveRecord::Base

  belongs_to :player
  has_many :profile_fields

  def display
    "<img src='#{flag_url}' />#{name}".html_safe
  end

  def name
    first_name + " " + surname
  end

  def origin
    origin_city.to_s + ", " + origin_state.to_s + ", " + origin_country.to_s
  end

  def age

    return "N/A" if dob.nil?

    age = Date.today.year - dob.year
    age -= 1 if Date.today < dob + age.years

    return age
    
  end

end

sw-rails/app/models/profile_field.rb
class ProfileField < ActiveRecord::Base
end

sw-rails/app/models/season.rb
class Season < ActiveRecord::Base
end

sw-rails/app/models/team.rb
class Team < ActiveRecord::Base

  belongs_to :club
  belongs_to :season
  belongs_to :competition
  belongs_to :grade

end

sw-rails/app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def index
    @matches = Match.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @matches }
    end
  end

  def show
    @match = Match.find(params[:id])
  end

  def new
    @match = Match.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @match }
    end
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
  end

  # POST /matches
  # POST /matches.xml
  def create
    @match = Match.new(params[:match])

    respond_to do |format|
      if @match.save
        format.html { redirect_to(@match, :notice => 'Match was successfully created.') }
        format.xml  { render :xml => @match, :status => :created, :location => @match }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @match.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /matches/1
  # PUT /matches/1.xml
  def update
    @match = Match.find(params[:id])

    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to(@match, :notice => 'Match was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @match.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.xml
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to(matches_url) }
      format.xml  { head :ok }
    end
  end
end

sw-rails/app/helpers/home_helper.rb
module HomeHelper
end

sw-rails/app/helpers/matches_helper.rb
module MatchesHelper

def bat_worm match
    acc = 0
    worm = []

    match.batsman_inningss.each do |inns|
        inns.balls.each do |ball|
            worm << [(inns.ordinal+1)/2, ball.ordinal, ball.batsman_value]
        end
    end

    dataset = []

    worm.sort{|x,y| x[0]*27+x[1] <=> y[0]*27+y[1]}.each do |dp|
       acc += dp[2].to_i
       dataset << [(dp[0]-1)*27 + dp[1], acc]
    end

    dataset
  end

def bowl_worm match
    acc = 0
    worm = []

    match.overs.each do |over|
        over.balls.each do |ball|
            acc += ball.bowler_value
            worm << [over_start_idx(over.ordinal) + ball.ordinal, acc]
        end
    end

    worm
  end

  def over_start_idx(idx)
    [0,6,12,18, 27,33,39,45, 54,60,66,72, 81,87,93,99][idx]
  end

end

sw-rails/app/helpers/records_helper.rb
module RecordsHelper

  def order_select(name, order_for_best)
    options = [["Best -> Worst", order_for_best],["Worst -> Best", (order_for_best == 'desc') ? 'asc' : 'desc']]
    select_tag(name, options_for_select(options))
  end

  def season_select(name)
    select_tag(name, options_for_select([['- Select Season -','-1']] + Team.all.collect{|t|t.season}.collect{|s|[s.name,s.id]}))
  end

  def player_select(name)
    select_tag(name, options_for_select([['- Select Player -','-1']] + Player.all.sort{|x,y|x.name <=> y.name}.collect{|p|[p.display,p.id]}))
  end

end

sw-rails/app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sw-rails/app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

sw-rails/app/views/matches/index.html.erb
<h1>Listing Matches</h1>

<table>
  <tr>
    <th>Opposition</th>
    <th>Season</th>
    <th>Round</th>
    <th>Date</th>
    <th>Time</th>
    <th>Actions</th>
  </tr>

<% @matches.each do |match| %>
  <tr>
      <td><%= match.opposition_team.name %></td>
      <td><%= match.team.season.name %></td>
      <td><%= match.round %></td>
      <td><%= match.datetime.strftime("%d/%m/%Y") %></td>
      <td><%= match.datetime.strftime("%H:%M") %></td>
    <td>
        <%= link_to 'Show', match %>
        <%= link_to 'Edit', edit_match_path(match) %>
        <%= link_to 'Destroy', match, :confirm => 'Are you sure?', :method => :delete %>
      </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Match', new_match_path %>

sw-rails/app/views/matches/new.html.erb
<h1>New match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

sw-rails/app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<table id="matchdetails">
    <caption>
        Match Details
    </caption>
    <tbody>
        <tr>
            <th>Opposition</th>
            <td><%= @match.opposition_team.name %></td>
        </tr>
        <tr>
            <th>Season</th>
            <td><%= @match.team.season.name %></td>
        </tr>
        <tr>
            <th>Round</th>
            <td><%= @match.round %></td>
        </tr>
        <tr>
            <th>Date</th>
            <td><%= @match.datetime.strftime("%d/%m/%Y") %></td>
        </tr>
        <tr>
            <th>Time</th>
            <td><%= @match.datetime.strftime("%H:%M") %></td>
        </tr>
    </tbody>
</table>

<table id="batinns">
    <caption>
        Batting Scorecard
    </caption>
    <thead>
        <tr>
            <th>Batsman</th>
            <th colspan="6">1st Over</th>
            <th colspan="6">2nd Over</th>
            <th colspan="6">3rd Over</th>
            <th colspan="9">4th Over</th>
            <th>Total</th>
        </tr>
    </thead>

    <tbody>
        <% @match.batsman_inningss.each do |inns| %>
            <tr>
                <td><%= inns.player.display %></td>
                <% (1..27).each do |ordinal| %>
                  <%= ball_td(inns.balls.select{|b|b.ordinal == ordinal}[0]) %>
                <% end %>
                <td>
                  <%= "#{inns.score} (#{inns.bf})" %>
                </td>
            </tr>
        <% end  %>
    </tbody>
</table>

<table id="bowlinns">
  <caption>Bowling Scorecard</caption>
  <thead>
    <tr>
      <th>Bowler</th>
      <% (1..9).each do |i| %>
        <th><%= i %></th>
      <% end %>
      <th>Total</th>
    </tr>
  </thead>

  <tbody>
    <% @match.overs.each do |over| %>
      <tr>
        <td><%= over.player.display %></td>
        <% (1..9).each do |ordinal| %>
          <%= ball_td(over.balls.select{|b|b.ordinal == ordinal}[0]) %>
        <% end %>
        <td>
          <%= "#{over.score}" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= javascript_include_tag("http://people.iola.dk/olau/flot/jquery.js") %>
<%= javascript_include_tag("http://people.iola.dk/olau/flot/jquery.flot.js") %>
<div class="chartContainer">
    <h1>The Worm</h1>
    <div id="worm" style="width:980px;height:300px;" />
</div>

<script type="text/javascript">
    $(function() {
        var ds_bat = <%= bat_worm(@match) %>;
        var ds_bowl = <%= bowl_worm(@match) %>;

        var bat_data = {
            label: "Steamboat Willies",
            data: ds_bat
        };

        var bowl_data = {
            label: "<%= @match.opposition_team.name %>",
            data: ds_bowl
        };

        var options = {
            legend: {
                show: true,
                position: "se",
                backgroundColor: null
            },
            xaxis: {
                tickSize:27
            }

        }

        $.plot($("#worm"), [bat_data, bowl_data], options);
    });
</script>