sw-rails/config/routes.rb
SwRails::Application.routes.draw do

  root :to => "home#index"

  get "/profiles/:id/career" => "profiles#career"
  get "/profiles/:id/batting" => "profiles#batting"
  get "/profiles/:id/bowling" => "profiles#bowling"

  get "/records" => "records#index"
  get "/records/runs/:scope/:order" => "records#runs"

  get "/admin" => "common#admin"

  resources :extra_types
  resources :dismissal_types
  resources :matches
  resources :opposition_teams
  resources :player_aliases
  resources :grades
  resources :competition_genres
  resources :teams
  resources :competitions
  resources :seasons
  resources :nicknames
  resources :profiles
  resources :memberships
  resources :clubs
  resources :players
  
end

sw-rails/app/models/ball.rb
class Ball < ActiveRecord::Base

  belongs_to :batsman_innings
  belongs_to :over
  belongs_to :dismissal_type
  belongs_to :extra_type

  def category
    return '7+' if batsman_value >= 7
    return '5' if batsman_value >= 5
    return '3-4' if batsman_value >= 3
    return '1' if batsman_value == 1
    return 'Dot' if batsman_value == 0
    return 'Extra' unless extra_type.nil?
    return 'Wicket' unless dismissal_type.nil?
    return '2' if batsman_value == 2
    return score
  end

end

sw-rails/app/models/bat_innings.rb
class BatInnings < ActiveRecord::Base

  belongs_to :player
  
end

sw-rails/app/models/batsman_innings.rb
class BatsmanInnings < ActiveRecord::Base

  belongs_to :match
  belongs_to :player
  has_many :balls

  def self.find_all_by_filter(order, filter)

    limit = filter[:limit] || 50
    order_sql = (order == 'desc') ? 'order by runs desc, bf asc' : 'order by runs asc, bf desc'
    tables = {'batsman_innings' => 'bi', 'balls' => 'b'}
    clause = ""
    params = []

    if filter[:season_id]
      tables['seasons'] = 's'
      tables['matches'] = 'm'
      tables['teams'] = 't'
      clause += "m.team_id = t.id and bi.match_id = m.id and t.season_id = s.id and s.id = #{filter[:season_id]} and "
    end

    if filter[:player_id]
      clause += "bi.player_id in (#{filter[:player_id]})"
    end

    tables_str = ""
    tables.each{|x,y|tables_str += "#{x} #{y}," }
    tables_str = tables_str[0..-2]

    sql = "select bi.*, sum(b.batsman_value) runs, count(b.batsman_value) bf " +
            "from #{tables_str} " +
            "where #{clause} bi.id = b.batsman_innings_id " +
            "group by bi.id " +
            "#{order_sql} " +
            "limit #{limit}"

    connection.execute(sql)
  end

  def score
    runs = 0
    balls.each do |ball|
      runs += ball.batsman_value
    end
    runs
  end

  def bf
    balls.count
  end

end

sw-rails/app/models/club.rb
class Club < ActiveRecord::Base

  

end

sw-rails/app/models/competition.rb
class Competition < ActiveRecord::Base

  belongs_to :competition_genre

end

sw-rails/app/models/dismissal_type.rb
class DismissalType < ActiveRecord::Base
end

sw-rails/app/models/extra_type.rb
class ExtraType < ActiveRecord::Base
end

sw-rails/app/models/grade.rb
class Grade < ActiveRecord::Base
end

sw-rails/app/models/match.rb
class Match < ActiveRecord::Base

  belongs_to :team
  belongs_to :opposition_team
  has_many :batsman_inningss
  has_many :overs

end

sw-rails/app/models/membership.rb
class Membership < ActiveRecord::Base
end

sw-rails/app/models/nickname.rb
class Nickname < ActiveRecord::Base

  belongs_to :player
  
end

sw-rails/app/models/over.rb
class Over < ActiveRecord::Base

  belongs_to :match
  belongs_to :player
  has_many :balls


  def score
    runs = 0
    balls.each do |ball|
      runs += ball.bowler_value
    end
    runs
  end

  def bf
    balls.count
  end

  def extras
    balls.select{|b|!b.extra_type.nil?}.count
  end

  def wickets
    balls.select{|b|!b.dismissal_type.nil?}.count
  end

end

sw-rails/app/models/player.rb
class Player < ActiveRecord::Base

  has_many :player_aliases
  has_many :nicknames
  has_one :profile

  def display
    profile.nil? ? code : profile.display
  end

  def name
    profile.nil? ? code : profile.name
  end

end

sw-rails/app/models/player_alias.rb
class PlayerAlias < ActiveRecord::Base

  belongs_to :player
  
end

sw-rails/app/models/profile.rb
class Profile < ActiveRecord::Base

  belongs_to :player
  has_many :profile_fields

  def display
    "<img src='#{flag_url}' />#{name}".html_safe
  end

  def name
    first_name + " " + surname
  end

  def origin
    origin_city.to_s + ", " + origin_state.to_s + ", " + origin_country.to_s
  end

  def age

    return "N/A" if dob.nil?

    age = Date.today.year - dob.year
    age -= 1 if Date.today < dob + age.years

    return age
    
  end

end

sw-rails/app/models/profile_field.rb
class ProfileField < ActiveRecord::Base
end

sw-rails/app/models/season.rb
class Season < ActiveRecord::Base
end

sw-rails/app/models/team.rb
class Team < ActiveRecord::Base

  belongs_to :club
  belongs_to :season
  belongs_to :competition
  belongs_to :grade

end

sw-rails/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def career
    @profile = Profile.find(params[:id])
  end

  def batting
    @profile = Profile.find(params[:id])
  end

  def bowling
    @profile = Profile.find(params[:id])
  end

  def new
    @profile = Profile.new
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to(@profile, :notice => 'Profile was successfully created.') }
        format.xml  { render :xml => @profile, :status => :created, :location => @profile }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to(@profile, :notice => 'Profile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end
end

sw-rails/app/helpers/home_helper.rb
module HomeHelper
end

sw-rails/app/helpers/matches_helper.rb
module MatchesHelper

def bat_worm match
    acc = 0
    worm = []

    match.batsman_inningss.each do |inns|
        inns.balls.each do |ball|
            worm << [(inns.ordinal+1)/2, ball.ordinal, ball.batsman_value]
        end
    end

    dataset = []

    worm.sort{|x,y| x[0]*27+x[1] <=> y[0]*27+y[1]}.each do |dp|
       acc += dp[2].to_i
       dataset << [(dp[0]-1)*27 + dp[1], acc]
    end

    dataset
  end

def bowl_worm match
    acc = 0
    worm = []

    match.overs.each do |over|
        over.balls.each do |ball|
            acc += ball.bowler_value
            worm << [over_start_idx(over.ordinal) + ball.ordinal, acc]
        end
    end

    worm
  end

  def over_start_idx(idx)
    [0,6,12,18, 27,33,39,45, 54,60,66,72, 81,87,93,99][idx]
  end

end

sw-rails/app/helpers/profiles_helper.rb
module ProfilesHelper

  def bat_bell(inns)
    arr = []
    inns.sort{|x,y|x.score <=> y.score}.each_with_index{|inns,idx|arr << [idx,inns.score]}
    arr
  end

end

sw-rails/app/helpers/records_helper.rb
module RecordsHelper

  def order_select(name, order_for_best)
    options = [["Best -> Worst", order_for_best],["Worst -> Best", (order_for_best == 'desc') ? 'asc' : 'desc']]
    select_tag(name, options_for_select(options))
  end

  def season_select(name)
    select_tag(name, options_for_select([['- Select Season -','-1']] + Team.all.collect{|t|t.season}.collect{|s|[s.name,s.id]}))
  end

  def player_select(name)
    select_tag(name, options_for_select([['- Select Player -','-1']] + Player.all.sort{|x,y|x.name <=> y.name}.collect{|p|[p.display,p.id]}))
  end

end

sw-rails/app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
    </div>

    <div>
        <%= f.label :surname %>
        <%= f.text_field :surname %>
    </div>

    <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>

    <div>
        <%= f.label :origin_city %>
        <%= f.text_field :origin_city %>
    </div>

    <div>
        <%= f.label :origin_state %>
        <%= f.text_field :origin_state %>
    </div>

    <div>
        <%= f.label :origin_country %>
        <%= f.text_field :origin_country %>
    </div>

    <div>
        <%= f.label :dob %>
        <%= f.text_field :dob %>
    </div>

    <div>
        <%= f.label :picture_url %>
        <%= f.text_field :picture_url %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sw-rails/app/views/profiles/_inns_table.html.erb
<table>
    <caption><%= @caption %></caption>
    <thead>
        <tr>
            <th>Score</th>
            <th>Against</th>
            <th>Date</th>
            <th>Time</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @inns.each do |i| %>
        <tr>
            <td><%= "#{i.score} (#{i.bf})" %></td>
            <td><%= i.match.opposition_team.name %></td>
            <td><%= i.match.datetime.strftime("%d-%m-%Y") %></td>
            <td><%= i.match.datetime.strftime("%H:%M") %></td>
            <td><%= link_to "Scorecard", i.match %></td>
        </tr>
        <% end %>
    </tbody>
</table>

sw-rails/app/views/profiles/_tabs.html.erb
<h1><%= @profile.display %></h1>

<ul class="tabs">
    <li><a href="/profiles/<%= @profile.id %>">Profile</a></li>
    <li><a href="/profiles/<%= @profile.id %>/career">Career</a></li>
    <li><a href="/profiles/<%= @profile.id %>/batting">Batting</a></li>
    <li><a href="/profiles/<%= @profile.id %>/bowling">Bowling</a></li>
</ul>

sw-rails/app/views/profiles/batting.html.erb
<%= render 'tabs' %>

<%
   inns = BatsmanInnings.find_all_by_player_id(@profile.player.id)
%>

<div>Matches: <%= inns.collect{|i|i.match_id}.uniq.count %></div>
<div>Innings: <%= inns.collect{|i|i.match_id}.count %></div>
<div>Runs: <%= inns.collect{|i|i.score}.sum %></div>
<div>Balls: <%= inns.collect{|i|i.bf}.sum %></div>

<%= inns_table("Best 5 Innings", inns.sort{|x,y|y.score <=> x.score}[0..4]) %>
<%= inns_table("Worst 5 Innings", inns.sort{|x,y|x.score <=> y.score}[0..4]) %>

<%
   balls = []
   inns.each{|i|balls << i.balls}
   bg = balls.flatten.group_by{|b|b.category}
   hist_ds = []
   bg.keys.sort.each{|bs|hist_ds << [bs,bg[bs].length]}
%>

<div class="chartContainer">
    <h1>Pies</h1>
    <div id="pie" style="width:400px;height:250px;" />
</div>

<div class="chartContainer">
    <h1>Batting Bell Curve</h1>
    <div id="bell" style="width:980px;height:300px;" />
</div>

<%= javascript_include_tag("http://people.iola.dk/olau/flot/jquery.js") %>
<%= javascript_include_tag("http://people.iola.dk/olau/flot/jquery.flot.js") %>
<%= javascript_include_tag("http://people.iola.dk/olau/flot/jquery.flot.pie.js") %>
<script type="text/javascript">
    $(function() {

        var pie_ds = [
            <% hist_ds.each do |dp| %>
            {label: "<%= dp[0] %>", data: <%= dp[1] %>},
            <% end %>
        ];
        
        $.plot($("#pie"), pie_ds, {
            series: {
                pie: {
                    show: true
                }
            }
        });

        var bbc_ds = <%= bat_bell(inns) %>;
        var bbc_options = {
            yaxis: {
                min: -50,
                max: 50,
                tickSize: 10
            }
        }
        $.plot($("#bell"), [bbc_ds], bbc_options);
    });
</script>

sw-rails/app/views/profiles/bowling.html.erb
<%= render 'tabs' %>

<%
   overs = Over.find_all_by_player_id(@profile.player.id)
%>

<table>
    <caption>Bowling Overview</caption>
    <tbody>
        <tr>
            <th>Matches</th>
            <td><%= overs.collect{|i|i.match_id}.uniq.count %></td>
        </tr>
        <tr>
            <th>Overs</th>
            <td><%= overs.collect{|i|i.match_id}.count %></td>
        </tr>
        <tr>
            <th>Runs Conceeded</th>
            <td><%= overs.collect{|i|i.score}.sum %></td>
        </tr>
        <tr>
            <th>Balls Bowled</th>
            <td><%= overs.collect{|i|i.bf}.sum %></td>
        </tr>
        <tr>
            <th>Extras</th>
            <td><%= overs.collect{|i|i.extras}.sum %></td>
        </tr>
        <tr>
            <th>Wickets</th>
            <td><%= overs.collect{|i|i.wickets}.sum %></td>
        </tr>
    </tbody>
</table>

<%= inns_table("Best 10 Overs", overs.sort{|x,y|x.score <=> y.score}[0..9]) %>
<%= inns_table("Worst 10 Overs", overs.sort{|x,y|y.score <=> x.score}[0..9]) %>

sw-rails/app/views/profiles/career.html.erb
<%= render 'tabs' %>

<%
   inns = BatsmanInnings.find_all_by_player_id(@profile.player.id)
%>

<div>Matches: <%= inns.collect{|i|i.match_id}.uniq.count %></div>

sw-rails/app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

sw-rails/app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>Player</th>
    <th>Age (days)</th>
    <th>Origin</th>
    <th>About...</th>
    <th>Actions</th>
  </tr>

<% @profiles.sort{|x,y| x.name <=> y.name}.each do |profile| %>
  <tr>
    <td><%= profile.display %></td>
    <td><%= profile.age %></td>
    <td><%= profile.origin %></td>
    <td><%= profile.blurb %></td>
    <td>
      <%= link_to 'Profile', profile %>
        <%= link_to 'Career',  "/profiles/#{profile.id}/career" %>
        <%= link_to 'Batting', "/profiles/#{profile.id}/batting" %>
        <%= link_to 'Bowling', "/profiles/#{profile.id}/bowling" %>
      <%= link_to 'Edit', edit_profile_path(profile) %>
      <%= link_to 'Destroy', profile, :confirm => 'Are you sure?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

sw-rails/app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

sw-rails/app/views/profiles/show.html.erb
<%= render 'tabs' %>

<table>
  <thead>
      <tr>
          <th>Nicknames</th>
          <th>Aliases</th>
      </tr>
  </thead>

  <tbody>
      <tr>
        <td>
          <% @profile.player.nicknames.each do |nickname| %>
            <div><%= nickname.name %></div>
          <% end %>
        </td>
        <td>
          <% @profile.player.player_aliases.each do |name| %>
            <div><%= name.name %></div>
          <% end %>
        </td>
      </tr>
  </tbody>

  <tfoot>
    <tr>
      <td>Create Nickame</td>
      <td>Create Alias</td>
    </tr>
  </tfoot>
</table>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

sw-rails/app/views/profiles/stats.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @profile.display %></h2>

<%
   inns = BatsmanInnings.find_all_by_player_id(@profile.player.id)
%>

<div>Matches: <%= inns.collect{|i|i.match_id}.uniq.count %></div>
<div>Innings: <%= inns.collect{|i|i.match_id}.count %></div>
<div>Runs: <%= inns.collect{|i|i.score}.sum %></div>
<div>Balls: <%= inns.collect{|i|i.bf}.sum %></div>

<%= inns_table("Best 5 Innings", inns.sort{|x,y|y.score <=> x.score}[0..4]) %>
<%= inns_table("Worst 5 Innings", inns.sort{|x,y|x.score <=> y.score}[0..4]) %>

<%= link_to 'Back', profiles_path %>